### ISSUE TITLE
Please add a related work

### ISSUE THREAD

**Issue by sunshangquan** [XLearning-SCU/Awesome-All-In-One-Image-Restoration#8]
[ECCV 2024] Restoring Images in Adverse Weather Conditions via Histogram Transformer
arXiv: https://arxiv.org/abs/2407.10172
Code: https://github.com/sunshangquan/Histoformer

**Comment by XLearning-SCU** [comment]
Thank you for your valuable suggestion! We have reviewed the paper and added it to the list. We appreciate your contribution to improving the repository.
