### ISSUE TITLE
add all-in-one medical image restoration

### ISSUE THREAD

**Issue by Yaziwel** [XLearning-SCU/Awesome-All-In-One-Image-Restoration#9]
Thank you for your excellent collection of papers on all-in-one image restoration. Could you please include our recent work on all-in-one medical image restoration?

ArXiv: https://arxiv.org/abs/2405.19769
GitHub: https://github.com/Yaziwel/All-In-One-Medical-Image-Restoration-via-Task-Adaptive-Routing

**Comment by XLearning-SCU** [comment]
Thank you for your valuable suggestion! We have reviewed the paper and added it to the list. We appreciate your contribution to improving the repository.
